[package]
name = "terdle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
rand = "0.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1